---
- name: Install FreeIPMI
  become: yes
  ansible.builtin.apt:
    name: freeipmi
    state: present

- name: Get IPMI exporter
  become: yes
  become_user: root
  get_url:
    url: "https://github.com/prometheus-community/ipmi_exporter/releases/download/v{{ IPMI_exporter_version }}/ipmi_exporter-{{ IPMI_exporter_version }}.{{ IPMI_exporter_arch }}.tar.gz"
    dest: "{{ IPMI_exporter_config_dir }}/sources/IPMI_exporter-{{ IPMI_exporter_version }}.{{ IPMI_exporter_arch }}.tar.gz"
    mode: 0644
    owner: root
    group: root

- name: Unzip IPMI exporter
  become: yes
  become_user: root
  unarchive:
    remote_src: yes
    src: "{{ IPMI_exporter_config_dir }}/sources/IPMI_exporter-{{ IPMI_exporter_version }}.{{ IPMI_exporter_arch }}.tar.gz"
    dest: "{{ IPMI_exporter_config_dir }}/sources/"
    creates: "{{ IPMI_exporter_config_dir }}/sources/ipmi_exporter-{{ IPMI_exporter_version }}.{{ IPMI_exporter_arch }}/"

- name: Copy exporter to PATH
  become: yes
  become_user: root
  copy:
    remote_src: yes
    src: "{{ IPMI_exporter_config_dir }}/sources/ipmi_exporter-{{ IPMI_exporter_version }}.{{ IPMI_exporter_arch }}/"
    dest: /usr/local/bin/IPMI_exporter
    mode: 0755
    owner: root
    group: root
  notify:
    - Restart IPMI exporter

- name: Create IPMI exporter user
  user:
    name: "{{ IPMI_exporter_user }}"
    comment: "IPMI exporter user"
    shell: /usr/sbin/nologin

- name: Exporters | IPMI exporter | Ensure IPMI exporter systemd unit
  become: yes
  become_user: root
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/IPMI-exporter.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_unitfile
  notify:
    - Restart IPMI exporter

- name: Exporters | blackbox exporter | Enable systemd service
  become: yes
  become_user: root
  systemd:
    name: "IPMI-exporter.service"
    enabled: yes
    daemon_reload: yes
    state: started
  when:
    - systemd_unitfile.changed
